services:
  mongodb:
    ports:
      - "27017:27017"
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ThisIsJustALocalInstance
